name: Reproducible build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SONARQUBE_ORG: ${{ secrets.SONARQUBE_ORG }}
  SONARQUBE_PROJECT_KEY: ${{ secrets.SONARQUBE_PROJECT_KEY }}
  SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Ensure cache directories exists
        run: |
          mkdir -p ${{ github.workspace }}/.nuget/packages
          mkdir -p ${{ github.workspace }}/.npm
          mkdir -p ${{ github.workspace }}/.net/tools

      - name: Cache nuget packages
        id: cache-nuget-packages
        uses: actions/cache@v5
        env:
          cache-name: nuget-packages
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/packages.lock.json') }}

      - name: Cache npm packages
        id: cache-npm-packages
        uses: actions/cache@v5
        env:
          cache-name: npm-packages
        with:
          path: ${{ github.workspace }}/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.npm_global_packages') }}

      - name: Cache dotnet tools package
        id: cache-dotnet-tools
        uses: actions/cache@v5
        env:
          cache-name: dotnet-tools
        with:
          path: ${{ github.workspace }}/.net/tools
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.net_tools') }}

      - name: Run spell-check
        run: |
          NPM_PACKAGES=${{ github.workspace }}/.npm

          docker build \
            --target spell_check \
            -f Dockerfile \
            --build-arg NPM_PACKAGES=$NPM_PACKAGES \
            .

      - name: Run dotnet format
        run: |
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          NUGET_PACKAGES=${{ github.workspace }}/.nuget/packages

          docker build \
            --target verify_dotnet_format \
            -f Dockerfile \
            --build-arg SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH \
            --build-arg NUGET_PACKAGES=$NUGET_PACKAGES \
            .

      - name: Run tests
        run: |
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          NUGET_PACKAGES=${{ github.workspace }}/.nuget/packages
          DOTNET_TOOLS=${{ github.workspace }}/.net/tools

          docker build \
            --target tests.linux-x64 \
            -f Dockerfile \
            --build-arg SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH \
            --build-arg NUGET_PACKAGES=$NUGET_PACKAGES \
            --secret id=sonarqube_org,env=SONARQUBE_ORG \
            --secret id=sonarqube_project_key,env=SONARQUBE_PROJECT_KEY \
            --secret id=sonarqube_token,env=SONARQUBE_TOKEN \
            --build-arg RUN_SONARQUBE=true \
            --build-arg DOTNET_TOOLS=$DOTNET_TOOLS \
            --output type=tar,dest=tests.linux-x64.tar,rewrite-timestamp=false \
            .

          mkdir tests.linux-x64
          tar -xf tests.linux-x64.tar -C tests.linux-x64

      - name: Publish
        run: |
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          NUGET_PACKAGES=${{ github.workspace }}/.nuget/packages
          DOTNET_TOOLS=${{ github.workspace }}/.net/tools

          docker build \
            --target files.linux-x64 \
            -f Dockerfile \
            --build-arg SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH \
            --build-arg NUGET_PACKAGES=$NUGET_PACKAGES \
            --secret id=sonarqube_org,env=SONARQUBE_ORG \
            --secret id=sonarqube_project_key,env=SONARQUBE_PROJECT_KEY \
            --secret id=sonarqube_token,env=SONARQUBE_TOKEN \
            --build-arg RUN_SONARQUBE=true \
            --build-arg DOTNET_TOOLS=$DOTNET_TOOLS \
            --output type=tar,dest=app.linux-x64.tar,rewrite-timestamp=false \
            .

          docker build \
            --target runtime.linux-x64 \
            -f Dockerfile \
            --build-arg SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH \
            --build-arg NUGET_PACKAGES=$NUGET_PACKAGES \
            --secret id=sonarqube_org,env=SONARQUBE_ORG \
            --secret id=sonarqube_project_key,env=SONARQUBE_PROJECT_KEY \
            --secret id=sonarqube_token,env=SONARQUBE_TOKEN \
            --build-arg RUN_SONARQUBE=true \
            --build-arg DOTNET_TOOLS=$DOTNET_TOOLS \
            -t tag1 \
            .

          mkdir app.linux-x64
          tar -xf app.linux-x64.tar -C app.linux-x64

      # - name: Verify reproducible build
      #   run: |
      #     SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
      #     NUGET_PACKAGES=${{ github.workspace }}/.nuget/packages

      #     docker build \
      #       --no-cache \
      #       --target runtime.linux-x64 \
      #       -f Dockerfile \
      #       --build-arg SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH \
      #       --build-arg NUGET_PACKAGES=$NUGET_PACKAGES \
      #       --build-arg RUN_SONARQUBE=false \
      #       -t tag2 \
      #       .

      #     wget -q -O diffoci https://github.com/reproducible-containers/diffoci/releases/download/v0.1.8/diffoci-v0.1.8.linux-amd64
      #     chmod +x ./diffoci
      #     ./diffoci diff --semantic docker://tag1 docker://tag2

      - name: Upload `tests`
        uses: actions/upload-artifact@v6
        with:
          name: tests.linux-x64
          path: |
            tests.linux-x64/

      - name: Upload `app`
        uses: actions/upload-artifact@v6
        with:
          name: app.linux-x64
          path: |
            app.linux-x64/
