name: Build and Test Docker Images

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build multi-stage image
              run: |
                  SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
                  docker build --target files.linux-x64 -f Dockerfile --build-arg SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH --output type=tar,dest=app.linux-x64.tar,rewrite-timestamp=false .
                  docker build --target runtime.linux-x64 -f Dockerfile --build-arg SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH .

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: app.linux-x64
                  path: |
                      app.linux-x64.tar
